### ISSUE TITLE
Description du sujet: Gestion d'un Cabinet medical

### ISSUE THREAD

**Issue by pbobc10** [senburbensnew/Immersion-BD-et-SQL-Oracle#8]
Ce que doit faire cette application, décrire textuellement ces structures et ses services

**Comment by pbobc10** [comment]
je viens d'ajouter un fichier qui contient la description du sujet. 
@rodelydouilly @senburbensnew @sdjim15

**Comment by senburbensnew** [comment]
> je viens d'ajouter un fichier qui contient la description du sujet.
> @rodelydouilly @senburbensnew @sdjim15

C’est compris. Je l’ai déjà consulté et l’intégrer dans le documeny pdf final. Je compte pusher très bientot
